# Generated by Django 3.0 on 2019-12-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='exchange_rate',
            field=models.IntegerField(default=1),
        ),
    ]
