# Generated by Django 3.0 on 2019-12-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_transfer_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='exchange_rate',
            field=models.FloatField(default=1.0),
        ),
    ]
