# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-21 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('memo', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('dst_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dst_account', to='erp.Account')),
                ('src_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='src_account', to='erp.Account')),
            ],
        ),
    ]
