# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_operatingexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
