# Generated by Django 3.0 on 2019-12-12 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191212_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 15, 40, 21, 172979, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 12, 15, 40, 21, 173527, tzinfo=utc)),
        ),
    ]
