# Generated by Django 3.0 on 2019-12-12 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191212_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
