# Generated by Django 3.0 on 2019-12-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20191212_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_price',
            field=models.IntegerField(default=0),
        ),
    ]
