# Generated by Django 3.0 on 2019-12-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_avg_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='shipping_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
