# Generated by Django 3.0 on 2019-12-17 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('inventory', '0008_auto_20191214_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_method',
            field=models.CharField(choices=[('ktj', 'ktj'), ('post', 'post')], default='ktj', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='platform',
            field=models.CharField(choices=[('shoppe', 'shoppe'), ('pcone', 'pcone'), ('group_buy', 'group_buy')], default='shoppe', max_length=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tax',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='shipping_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax',
            field=models.IntegerField(default=0),
        ),
    ]
